server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0: # 입력 바인딩
          destination: order-accepted # 바인더를 연결할 대상의 메시지 브로커 내에서의 이름 (래빗 MQ의 익스체인지)
          group: ${spring.application.name} # 소비자 그룹
        packlabel-out-0: # 출력 바인딩
          destination: order-dispatched # 바인더를 연결할 대상의 메시지 브로커 내에서의 이름 (래빗 MQ의 익스체인지)
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

